http://localhost:3800/api/home

###

http://localhost:3800/api/pruebas

###

POST http://localhost:3800/api/register
Content-Type: application/x-www-form-urlencoded

name=Carmen&surname=Moreno&nick=Nena&email=cmcandau@hotmail.com&password=1049
###

POST http://localhost:3800/api/login
Content-Type: application/x-www-form-urlencoded

gettoken=true&email=cmcandau@hotmail.com&password=1049

###

POST http://localhost:3800/api/login
Content-Type: application/x-www-form-urlencoded

email=mgastalver@gmail.com&password=4651

###

POST http://localhost:3800/api/login
Content-Type: application/x-www-form-urlencoded

gettoken=true&email=mgastalver@gmail.com&password=4651

###

http://localhost:3800/api/pruebas
Authorization: 'tokendepega'

###

POST /api/upload-image-user/5ae744e24d664b0540866b36 HTTP/1.1
Host: localhost:3800
Authorization:  "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1YWU3NDRlMjRkNjY0YjA1NDA4NjZiMzYiLCJuYW1lIjoiTWlndWVsIiwic3VybmFtZSI6Ikdhc3RhbHZlciIsIm5pY2siOiJDaGluZXNlIiwiZW1haWwiOiJtZ2FzdGFsdmVyQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJpbWFnZSI6bnVsbCwiaWF0IjoxNTI1NDUwMTQ3LCJleHAiOjE1MjgwNDIxNDd9.whx9rVKovEsrNT2Wh1-Ki48peGU_ZsGBK8BQOeUrrzQ"
Cache-Control: no-cache
Postman-Token: e6b7e3b3-1882-4d20-8a4f-8c9c027d6ae4
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename=""
Content-Type:


------WebKitFormBoundary7MA4YWxkTrZu0gW--

http://localhost:3800/api/pruebas
Authorization: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1YWU3NDRlMjRkNjY0YjA1NDA4NjZiMzYiLCJuYW1lIjoiTWlndWVsIiwic3VybmFtZSI6Ikdhc3RhbHZlciIsIm5pY2siOiJDaGluZXNlIiwiZW1haWwiOiJtZ2FzdGFsdmVyQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJpbWFnZSI6bnVsbCwiaWF0IjoxNTI1MTE1MDI4LCJleHAiOjE1Mjc3MDcwMjh9.LcjLAdVnvhA-HEPC5U8S4qrRDgFX6JN11jGZxut5xPo"

###

http://localhost:3800/api/user/5ae75264ca6fde093067aab4
Authorization: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1YWU3NDRlMjRkNjY0YjA1NDA4NjZiMzYiLCJuYW1lIjoiTWlndWVsIiwic3VybmFtZSI6Ikdhc3RhbHZlciIsIm5pY2siOiJDaGluZXNlIiwiZW1haWwiOiJtZ2FzdGFsdmVyQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJpbWFnZSI6bnVsbCwiaWF0IjoxNTI1MTE1MDI4LCJleHAiOjE1Mjc3MDcwMjh9.LcjLAdVnvhA-HEPC5U8S4qrRDgFX6JN11jGZxut5xPo"

###

http://localhost:3800/api/user/5ae75264ca6fde093067aab
Authorization: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1YWU3NDRlMjRkNjY0YjA1NDA4NjZiMzYiLCJuYW1lIjoiTWlndWVsIiwic3VybmFtZSI6Ikdhc3RhbHZlciIsIm5pY2siOiJDaGluZXNlIiwiZW1haWwiOiJtZ2FzdGFsdmVyQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJpbWFnZSI6bnVsbCwiaWF0IjoxNTI1MTE1MDI4LCJleHAiOjE1Mjc3MDcwMjh9.LcjLAdVnvhA-HEPC5U8S4qrRDgFX6JN11jGZxut5xPo"

###


http://localhost:3800/api/users/1
Authorization: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1YWU3NDRlMjRkNjY0YjA1NDA4NjZiMzYiLCJuYW1lIjoiTWlndWVsIiwic3VybmFtZSI6Ikdhc3RhbHZlciIsIm5pY2siOiJDaGluZXNlIiwiZW1haWwiOiJtZ2FzdGFsdmVyQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJpbWFnZSI6bnVsbCwiaWF0IjoxNTI1MTE1MDI4LCJleHAiOjE1Mjc3MDcwMjh9.LcjLAdVnvhA-HEPC5U8S4qrRDgFX6JN11jGZxut5xPo"

###

PUT http://localhost:3800/api/update-user/5ae75264ca6fde093067aab4
Authorization: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1YWU3NTI2NGNhNmZkZTA5MzA2N2FhYjQiLCJuYW1lIjoiQ2FybWVuIiwic3VybmFtZSI6Ik1vcmVubyIsIm5pY2siOiJuZW5hIiwiZW1haWwiOiJjbWNhbmRhdUBob3RtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJpbWFnZSI6bnVsbCwiaWF0IjoxNTI1MTMzOTA5LCJleHAiOjE1Mjc3MjU5MDl9.0vc2XV-UU0TzqefkjnFN99GnbWBzVHE4H5ol7TKjCHg"
Content-Type: application/x-www-form-urlencoded

nick=Nena
###

POST http://localhost:3800/api/upload-image-user/5ae744e24d664b0540866b36
Content-Type: form-data
Authorization: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1YWU3NDRlMjRkNjY0YjA1NDA4NjZiMzYiLCJuYW1lIjoiTWlndWVsIiwic3VybmFtZSI6Ikdhc3RhbHZlciIsIm5pY2siOiJDaGluZXNlIiwiZW1haWwiOiJtZ2FzdGFsdmVyQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJpbWFnZSI6bnVsbCwiaWF0IjoxNTI1MTM2MzAzLCJleHAiOjE1Mjc3MjgzMDN9.ibOS_ikfpVeVK_Kjc6jyswl5U5Y05KkvpdI7Foeg9yo"

< C:\Users\Miguel\Pictures\avion.jpg


###

POST /api/upload-image-user/5ae744e24d664b0540866b36 HTTP/1.1
Host: localhost:3800
Authorization:  "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1YWU3NDRlMjRkNjY0YjA1NDA4NjZiMzYiLCJuYW1lIjoiTWlndWVsIiwic3VybmFtZSI6Ikdhc3RhbHZlciIsIm5pY2siOiJDaGluZXNlIiwiZW1haWwiOiJtZ2FzdGFsdmVyQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJpbWFnZSI6bnVsbCwiaWF0IjoxNTI1NDUwMTQ3LCJleHAiOjE1MjgwNDIxNDd9.whx9rVKovEsrNT2Wh1-Ki48peGU_ZsGBK8BQOeUrrzQ"
Cache-Control: no-cache
Postman-Token: 09fbe57f-94cc-4d8e-9f91-f40a126b9f56
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="gorila.jpg"
Content-Type: image/jpeg


------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
